// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlp2TSV5SXlSeYZJBaU99ZG8IXwScrtE4',
    appId: '1:870779011541:web:22d1ee45de313b52eb3d5c',
    messagingSenderId: '870779011541',
    projectId: 'chat-is-this-real',
    authDomain: 'chat-is-this-real.firebaseapp.com',
    storageBucket: 'chat-is-this-real.appspot.com',
    measurementId: 'G-XGV89LYZ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYhJNeP3RkZyKUDsel5HVGSySvTvE0aI',
    appId: '1:870779011541:android:b2f3c7b5e0f02832eb3d5c',
    messagingSenderId: '870779011541',
    projectId: 'chat-is-this-real',
    storageBucket: 'chat-is-this-real.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuEiv_COLN4ip-nNmNGKlsiZDLvXGToBQ',
    appId: '1:870779011541:ios:3021c7ef7f3ccc43eb3d5c',
    messagingSenderId: '870779011541',
    projectId: 'chat-is-this-real',
    storageBucket: 'chat-is-this-real.appspot.com',
    iosBundleId: 'com.example.chatIsThisRealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuEiv_COLN4ip-nNmNGKlsiZDLvXGToBQ',
    appId: '1:870779011541:ios:3021c7ef7f3ccc43eb3d5c',
    messagingSenderId: '870779011541',
    projectId: 'chat-is-this-real',
    storageBucket: 'chat-is-this-real.appspot.com',
    iosBundleId: 'com.example.chatIsThisRealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlp2TSV5SXlSeYZJBaU99ZG8IXwScrtE4',
    appId: '1:870779011541:web:975ad85542295b91eb3d5c',
    messagingSenderId: '870779011541',
    projectId: 'chat-is-this-real',
    authDomain: 'chat-is-this-real.firebaseapp.com',
    storageBucket: 'chat-is-this-real.appspot.com',
    measurementId: 'G-S2KEJXNFR8',
  );
}
